# Generated by Django 4.1.1 on 2022-09-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='缩写')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(verbose_name='回数')),
                ('mv', models.FloatField(verbose_name='门尼值')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='回炼')),
                ('shipment_status', models.BooleanField(default=False, verbose_name='出货状态')),
            ],
            options={
                'verbose_name': '详细信息',
                'verbose_name_plural': '详细信息',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='品名')),
                ('mv', models.CharField(max_length=255, verbose_name='门尼')),
                ('mv_min', models.FloatField(verbose_name='最小值')),
                ('mv_max', models.FloatField(verbose_name='最大值')),
                ('temperature', models.IntegerField(blank=True, default=100, verbose_name='温度')),
                ('rotor', models.CharField(default='ML 1+4', max_length=255, verbose_name='转子')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '品名清单',
                'verbose_name_plural': '品名清单',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(verbose_name='批号')),
            ],
            options={
                'verbose_name': '批号',
                'verbose_name_plural': '批号',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, verbose_name='出表时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.item', verbose_name='品名')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.lot', verbose_name='批号')),
            ],
            options={
                'verbose_name': '素炼成绩表',
                'verbose_name_plural': '素炼成绩表',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作员',
                'verbose_name_plural': '操作员',
            },
        ),
        migrations.CreateModel(
            name='DetailChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_log', models.CharField(max_length=255, verbose_name='变更记录')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.detail')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mixs.productionplan'),
        ),
    ]
