# Generated by Django 4.1.1 on 2022-10-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixs', '0002_monthlist_personlist_attendancelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='MonthList',
        ),
        migrations.DeleteModel(
            name='PersonList',
        ),
    ]
