# Generated by Django 4.1.1 on 2022-10-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField(verbose_name='日期')),
                ('type', models.IntegerField(choices=[(0, '平日'), (0, '休日'), (0, '法定')], verbose_name='日期类型')),
            ],
            options={
                'verbose_name': '月日清单',
                'verbose_name_plural': '月日清单',
            },
        ),
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='人员编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '人员清单',
                'verbose_name_plural': '人员清单',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '白班'), (1, '夜班')], verbose_name='白班夜班')),
                ('worktime', models.IntegerField(verbose_name='出勤时间')),
                ('overtime', models.IntegerField(verbose_name='加班时间')),
                ('absencetime', models.IntegerField(verbose_name='缺勤时间')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.monthlist', verbose_name='日期')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.personlist', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '出勤记录',
                'verbose_name_plural': '出勤记录',
            },
        ),
    ]
