# Generated by Django 4.1.1 on 2022-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='worktime',
            field=models.IntegerField(default=8, verbose_name='出勤时间'),
        ),
        migrations.AlterField(
            model_name='monthlist',
            name='days',
            field=models.DateField(blank=True, verbose_name='日期'),
        ),
    ]
