# Generated by Django 4.1.1 on 2022-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancelog_worktime_alter_monthlist_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlist',
            name='days',
            field=models.DateField(blank=True, verbose_name='出表时间'),
        ),
    ]
