# Generated by Django 4.1.1 on 2022-10-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_days_monthlist_day_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlist',
            old_name='type',
            new_name='type_month',
        ),
    ]
