# Generated by Django 4.1.1 on 2022-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_monthlist_day_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlist',
            name='type_month',
            field=models.IntegerField(choices=[(0, '平日'), (1, '休日'), (2, '法定')], verbose_name='日期类型'),
        ),
    ]
