# Generated by Django 4.1.1 on 2022-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '计划', 'verbose_name_plural': '计划'},
        ),
        migrations.AddField(
            model_name='testresult',
            name='eb',
            field=models.FloatField(blank=True, default=0, verbose_name='EB'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='fmax',
            field=models.FloatField(blank=True, default=0, verbose_name='Fmax'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='fmin',
            field=models.FloatField(blank=True, default=0, verbose_name='Fmin'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='hs',
            field=models.FloatField(blank=True, default=0, verbose_name='HS'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='m_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='M %'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='scorch',
            field=models.FloatField(blank=True, default=0, verbose_name='焦烧'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='sg',
            field=models.FloatField(blank=True, default=0, verbose_name='SG'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='t10',
            field=models.FloatField(blank=True, default=0, verbose_name='T10'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='t90',
            field=models.FloatField(blank=True, default=0, verbose_name='T90'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tb',
            field=models.FloatField(blank=True, default=0, verbose_name='TB'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='batch',
            field=models.IntegerField(blank=True, default=0, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='mv',
            field=models.FloatField(blank=True, default=0, verbose_name='门尼值'),
        ),
    ]
