# Generated by Django 4.1.1 on 2022-10-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0004_alter_testresult_batch_alter_testresult_eb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='eb_max',
            field=models.FloatField(blank=True, null=True, verbose_name='EB最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='eb_min',
            field=models.FloatField(blank=True, null=True, verbose_name='EB最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='fmax_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Fmax最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='fmax_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Fmax最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='fmin_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Fmin最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='fmin_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Fmin最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='hs_max',
            field=models.FloatField(blank=True, null=True, verbose_name='HS最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='hs_min',
            field=models.FloatField(blank=True, null=True, verbose_name='HS最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='m_percent_max',
            field=models.FloatField(blank=True, null=True, verbose_name='M%最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='m_percent_min',
            field=models.FloatField(blank=True, null=True, verbose_name='M%最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='scorch_max',
            field=models.FloatField(blank=True, null=True, verbose_name='焦烧最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='scorch_min',
            field=models.FloatField(blank=True, null=True, verbose_name='焦烧最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='sg_max',
            field=models.FloatField(blank=True, null=True, verbose_name='SG最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='sg_min',
            field=models.FloatField(blank=True, null=True, verbose_name='SG最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='t10_max',
            field=models.FloatField(blank=True, null=True, verbose_name='T10最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='t10_min',
            field=models.FloatField(blank=True, null=True, verbose_name='T10最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='t90_max',
            field=models.FloatField(blank=True, null=True, verbose_name='T90最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='t90_min',
            field=models.FloatField(blank=True, null=True, verbose_name='T90最小值'),
        ),
        migrations.AddField(
            model_name='item',
            name='tb_max',
            field=models.FloatField(blank=True, null=True, verbose_name='TB最大值'),
        ),
        migrations.AddField(
            model_name='item',
            name='tb_min',
            field=models.FloatField(blank=True, null=True, verbose_name='TB最小值'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mv_max',
            field=models.FloatField(verbose_name='MV最大值'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mv_min',
            field=models.FloatField(verbose_name='MV最小值'),
        ),
    ]
