# Generated by Django 4.1.1 on 2022-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0005_item_eb_max_item_eb_min_item_fmax_max_item_fmax_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='temperature',
        ),
        migrations.AddField(
            model_name='item',
            name='m_percent_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='M%数值'),
        ),
        migrations.AddField(
            model_name='item',
            name='m_percent_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='M%单位'),
        ),
        migrations.AddField(
            model_name='item',
            name='mdr_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='MDR时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='mdr_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='MDR温度'),
        ),
        migrations.AddField(
            model_name='item',
            name='mv_duration',
            field=models.CharField(default='1+4', max_length=20, verbose_name='门尼时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='mv_temperature',
            field=models.IntegerField(blank=True, default=125, verbose_name='门尼温度'),
        ),
        migrations.AddField(
            model_name='item',
            name='rotor',
            field=models.IntegerField(choices=[(0, 'ML'), (1, 'Ms')], default=0, verbose_name='转子'),
        ),
        migrations.AddField(
            model_name='item',
            name='scorch_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='焦烧温度'),
        ),
        migrations.AddField(
            model_name='item',
            name='scorch_type',
            field=models.CharField(default='T=5', max_length=20, verbose_name='焦烧类型'),
        ),
        migrations.AddField(
            model_name='item',
            name='tb_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TB单位'),
        ),
        migrations.AddField(
            model_name='item',
            name='vulcanization_disc_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='圆片时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='vulcanization_square_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='方片时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='vulcanization_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='硫化温度'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='门尼'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mv_max',
            field=models.FloatField(blank=True, null=True, verbose_name='MV最大值'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mv_min',
            field=models.FloatField(blank=True, null=True, verbose_name='MV最小值'),
        ),
    ]
