# Generated by Django 4.1.1 on 2022-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0006_remove_item_temperature_item_m_percent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='scorch_temperature',
            field=models.IntegerField(blank=True, default=125, null=True, verbose_name='焦烧温度'),
        ),
    ]
