# Generated by Django 4.1.1 on 2022-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0007_alter_item_scorch_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='m_percent_unit',
            field=models.IntegerField(choices=[(0, 'kgf/cm2'), (1, 'Mpa')], default=0, verbose_name='M%单位'),
        ),
    ]
