# Generated by Django 4.1.1 on 2022-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixb', '0010_alter_item_m_percent_type_alter_item_tb_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='eb_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='EB最大值'),
        ),
        migrations.AlterField(
            model_name='item',
            name='eb_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='EB最小值'),
        ),
    ]
